#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2

# If you want to allow UTF-8 BOM in PHP files set this variable to true.
allowutf8bominphp=$(git config --bool hooks.allowutf8bominphp)
if [ "$allowutf8bominphp" != "true" ] &&
    test $(head -c 3 $(git diff --cached --name-only) | xxd -p | grep -c 'efbbbf' | 
        awk '{ sum += $1; } END { print sum; }' "$@") != 0
then
	cat <<\EOF
Error: Attempt to add a PHP file with UTF-8 BOM

This can cause problems. To see the list of PHP files with BOM try: 
  find . -iname '*.php' -exec grep -lI $'\xEF\xBB\xBF' {} \;

You can disable this check by setting the following in the [hooks] section of your git config file:
  allowutf8bominphp=true

EOF
	exit 1
fi

# If you want to allow trailing whitespaces in PHP files set this variable to true.
allowtrailingwhitespacesinphp=$(git config --bool hooks.allowtrailingwhitespacesinphp)
if [ "$allowtrailingwhitespacesinphp" != "true" ] &&
    test "$(git diff-index --check --cached $against -- | grep '\.php:')"
then
	cat <<\EOF
Error: Attempt to commit a PHP file with a trailing whitespace

This can cause problems. To see the list of PHP files with a trailing whitespace try: 
EOF

    echo "  git diff-index --check --cached $against -- | grep '\.php:' "

	cat <<\EOF

You can disable this check by setting the following in the [hooks] section of your git config file:
  allowtrailingwhitespacesinphp=true

EOF
	exit 1
fi
